apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: BACKEND_IMAGE
        ports:
        - containerPort: 3001
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: database-url
        - name: GOOGLE_CLOUD_PROJECT
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: project-id
        - name: GOOGLE_CLOUD_STORAGE_BUCKET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: storage-bucket
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        - name: cache-volume
          mountPath: /app/cache
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"
      volumes:
      - name: google-cloud-key
        secret:
          secretName: google-cloud-key
      - name: cache-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3001
  selector:
    app: backend 